"""Constants for T2C Clermont-Ferrand."""

DOMAIN = "t2c_clermontferrand"
GLOBAL_ENTRY_ID = "_global_entry_id"

DATASET_API_URL = (
    "https://www.data.gouv.fr/api/1/datasets/"
    "syndicat-mixte-des-transports-en-commun-de-lagglomeration-clermontoise-"
    "smtc-ac-reseau-t2c-gtfs-gtfs-rt/"
)
GTFS_RT_TRIP_UPDATES_URL = (
    "https://proxy.transport.data.gouv.fr/resource/"
    "t2c-clermont-gtfs-rt-trip-update"
    "?token=xdgqKBTAzhw4DSPz6zeGc4c5eW0LhwztcGv4-vpzP4U"
)
QR_TIMETABLE_API_URL = "https://qrcode.t2c.fr/api/timetable"
LINE_ALERTS_API_URL = "https://api.t2c.fr/siv/alerts/by-line/{line_id}"

CONF_LINE_NAME = "line_name"
CONF_LINE_ID = "line_id"
CONF_DIRECTION_NAME = "direction_name"
CONF_DIRECTION_ID = "direction_id"
CONF_STOP_NAME = "stop_name"
CONF_STOP_ID = "stop_id"
CONF_DEPARTURE_LIMIT = "departure_limit"
CONF_STOPS = "stops"

DEFAULT_SCAN_INTERVAL_MINUTES = 1
DEFAULT_DEPARTURE_LIMIT = 5
MIN_DEPARTURE_LIMIT = 1
MAX_DEPARTURE_LIMIT = 10

ATTR_LINE = "line"
ATTR_ROUTE_ID = "route_id"
ATTR_ROUTE_COLOR = "route_color"
ATTR_ROUTE_TEXT_COLOR = "route_text_color"
ATTR_DIRECTION = "direction"
ATTR_STOP = "stop"
ATTR_STOP_ID = "stop_id"
ATTR_LABEL = "label"
ATTR_NEXT_PASSAGES = "next_passages"
ATTR_RAW_PASSAGES = "raw_passages"
ATTR_DEPARTURES = "departures"
ATTR_MESSAGES = "messages"
ATTR_ALERTS = "alerts"
ATTR_ALERT_ICON = "alert_icon"
ATTR_ALERT_TEXT = "alert_text"
ATTR_ALERT_TITLE = "alert_title"
ATTR_COUNT = "count"
ATTR_SCOPE = "scope"
ATTR_LEVEL = "level"
ATTR_PRIORITY = "priority"
ATTR_UPDATED_AT = "updated_at"
ATTR_AFFECTED_ROUTES = "affected_routes"
ATTR_HAS_ALERT = "has_alert"
ATTR_DESTINATION = "destination"
ATTR_REALTIME = "realtime"
ATTR_DUE_AT = "due_at"
ATTR_MINUTES = "minutes"
ATTR_INFO = "info"
ATTR_TRIP_ID = "trip_id"
ATTR_VEHICLE_ID = "vehicle_id"
ATTR_STATUS = "status"
ATTR_THEORETICAL = "theoretical"
ATTR_SCHEDULED_AT = "scheduled_at"
ATTR_ESTIMATED_AT = "estimated_at"
ATTR_VALID_FROM = "valid_from"
ATTR_VALID_UNTIL = "valid_until"
ATTR_LINE_REFS = "line_refs"
ATTR_STOP_REFS = "stop_refs"
